

spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB

server:
  port: 8080

post:
  image:
    local:
      url: /Users/arunvijay/Desktop/littlebird



kafka:
  topic:
    post: post-tweet-topic
    metadata: post-metadata-topic
  partition: 3
  replication-factor: 1
  bootstrap:
    url: "http://127.0.0.1:9092"

